import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ul className="flex mb-4">
          <li className="mr-6">
            <a className="text-blue-500 hover:text-blue-800" href="/">
              Secrets leaked
            </a>
          </li>
          <li className="mr-6">
            <a className="text-blue-500 hover:text-blue-800" href="/no-leak">
              No leak (server action different file)
            </a>
          </li>

          <li className="mr-6">
            <a
              className="text-blue-500 hover:text-blue-800"
              href="/no-leak-env-var-moved-outside"
            >
              No leak (env var moved outside server component)
            </a>
          </li>
        </ul>

        {children}
      </body>
    </html>
  );
}
